const translations = {
  hi: {
    'Monthly savings': 'मासिक बचत',
    'Member contribution': 'सदस्य योगदान',
    'Loan report': 'कर्ज रिपोर्ट',
    'Repayment report': 'भुगतान रिपोर्ट',
    'Interest report': 'ब्याज रिपोर्ट',
    'Penalty report': 'जुर्माना रिपोर्ट',
    'Transaction statement': 'लेन-देन विवरण',
    'Balance sheet': 'बैलेंस शीट',
    'Financial summary': 'वित्तीय सारांश',
    'Attendance report': 'उपस्थिति रिपोर्ट',
    'Goals report': 'लक्ष्य रिपोर्ट',
    'Emergency fund report': 'आपातकालीन निधि रिपोर्ट',
    'Meetings report': 'बैठक रिपोर्ट',
    'Documents report': 'दस्तावेज़ रिपोर्ट',
    'Members report': 'सदस्य रिपोर्ट',
    'Total savings': 'कुल बचत',
    'Outstanding loans': 'बकाया कर्ज',
    'Group balance': 'समूह शेष',
    'Total members': 'कुल सदस्य',
    Income: 'आय',
    Expenses: 'खर्च',
    Savings: 'बचत',
    'Loans outstanding': 'बकाया कर्ज',
    Available: 'उपलब्ध',
    Used: 'उपयोग',
    Remaining: 'शेष',
  },
  mr: {
    'Monthly savings': 'मासिक बचत',
    'Member contribution': 'सदस्य योगदान',
    'Loan report': 'कर्ज अहवाल',
    'Repayment report': 'परतफेड अहवाल',
    'Interest report': 'व्याज अहवाल',
    'Penalty report': 'दंड अहवाल',
    'Transaction statement': 'व्यवहार विवरण',
    'Balance sheet': 'ताळेबंद',
    'Financial summary': 'आर्थिक सारांश',
    'Attendance report': 'उपस्थिती अहवाल',
    'Goals report': 'ध्येय अहवाल',
    'Emergency fund report': 'आपत्कालीन निधी अहवाल',
    'Meetings report': 'बैठक अहवाल',
    'Documents report': 'दस्तऐवज अहवाल',
    'Members report': 'सदस्य अहवाल',
    'Total savings': 'एकूण बचत',
    'Outstanding loans': 'बाकी कर्जे',
    'Group balance': 'गट शिल्लक',
    'Total members': 'एकूण सदस्य',
    Income: 'उत्पन्न',
    Expenses: 'खर्च',
    Savings: 'बचत',
    'Loans outstanding': 'बाकी कर्जे',
    Available: 'उपलब्ध',
    Used: 'वापरले',
    Remaining: 'शिल्लक',
  },
}

export function localizeReportValue(value, language) {
  if (typeof value !== 'string' || language === 'en') return value
  return translations[language]?.[value] || value
}
